### ISSUE TITLE
点击全局捕获异常崩溃

### ISSUE THREAD

**Issue by ciscolxh** [goldze/MVVMHabit#5]
`h: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                         rx.exceptions.OnErrorNotImplementedException: For input string: "a"
                             at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                             at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                             at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                             at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
                             at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                             at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
                             at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                             at rx.internal.operators.OperatorThrottleFirst$1.onNext(OperatorThrottleFirst.java:53)
                             at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23)
                             at android.view.View.performClick(View.java:5640)
                             at android.view.View$PerformClick.run(View.java:22455)
                             at android.os.Handler.handleCallback(Handler.java:751)
                             at android.os.Handler.dispatchMessage(Handler.java:95)
                             at android.os.Looper.loop(Looper.java:154)
                             at android.app.ActivityThread.main(ActivityThread.java:6196)
                             at java.lang.reflect.Method.invoke(Native Method)
                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                          Caused by: java.lang.NumberFormatException: For input string: "a"
                             at java.lang.Integer.parseInt(Integer.java:521)
                             at java.lang.Integer.parseInt(Integer.java:556)
                             at com.goldze.mvvmhabit.ui.vm.DemoViewModel$5.call(DemoViewModel.java:93)
                             at me.goldze.mvvmhabit.binding.command.BindingCommand.execute(BindingCommand.java:51)
                             at me.goldze.mvvmhabit.binding.viewadapter.view.ViewAdapter$2.call(ViewAdapter.java:47)
                             at me.goldze.mvvmhabit.binding.viewadapter.view.ViewAdapter$2.call(ViewAdapter.java:43)
                             at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                             at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                             at rx.internal.operators.OperatorThrottleFirst$1.onNext(OperatorThrottleFirst.java:53) 
                             at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23) 
                             at android.view.View.performClick(View.java:5640) 
                             at android.view.View$PerformClick.run(View.java:22455) 
                             at android.os.Handler.handleCallback(Handler.java:751) 
                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                             at android.os.Looper.loop(Looper.java:154) 
                             at android.app.ActivityThread.main(ActivityThread.java:6196) 
                             at java.lang.reflect.Method.invoke(Native Method) 
                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) `

**Comment by goldze** [comment]
本来就是故意让它崩溃的....为了验证该异常的捕获
